import { useEffect, useRef, useState } from 'react';
import { Activity, Briefcase, Code2, FolderGit2, Home, Mail, Moon, Search, Sun, User, X } from 'lucide-react';
import { projects } from '../../data/portfolio';
import type { Project } from '../../types';

interface Props { isOpen: boolean; onClose: () => void; isDark: boolean; toggleTheme: () => void; onSelectProject: (project: Project) => void; recruiterMode: boolean; toggleRecruiter: () => void; }
const nav = [['hero', 'Command Center — Home', Home], ['about', 'Player Profile — About', User], ['skills', 'Skill Tree — Skills', Code2], ['experience', 'Mission History — Experience', Briefcase], ['projects', 'Project Worlds — Projects', FolderGit2], ['contact', 'Communication Portal — Contact', Mail]] as const;
export default function CommandPalette({ isOpen, onClose, isDark, toggleTheme, onSelectProject, recruiterMode, toggleRecruiter }: Props) {
  const [query, setQuery] = useState(''); const input = useRef<HTMLInputElement>(null);
  useEffect(() => { if (!isOpen) return; setQuery(''); const previous = document.activeElement as HTMLElement; window.setTimeout(() => input.current?.focus(), 0); const key = (event: KeyboardEvent) => { if (event.key === 'Escape') onClose(); }; window.addEventListener('keydown', key); return () => { window.removeEventListener('keydown', key); previous?.focus(); }; }, [isOpen, onClose]);
  if (!isOpen) return null;
  const match = (value: string) => value.toLowerCase().includes(query.toLowerCase());
  const found = projects.filter(project => match(project.title) || project.technologies.some(match));
  const go = (id: string) => { onClose(); window.setTimeout(() => document.getElementById(id)?.scrollIntoView({ behavior: 'smooth' }), 0); };
  return <div className="command-palette-backdrop" onMouseDown={event => { if (event.target === event.currentTarget) onClose(); }}><section className="command-palette-dialog" role="dialog" aria-modal="true" aria-label="Command palette"><div className="command-search-bar"><Search /><input ref={input} value={query} onChange={event => setQuery(event.target.value)} placeholder="Navigate or search project worlds…" /><button className="close-btn" onClick={onClose} aria-label="Close palette"><X /></button></div><div className="command-list">{!query && <><span className="command-group-title">QUICK NAVIGATION</span>{nav.map(([id, label, Icon]) => <button className="command-item" key={id} onClick={() => go(id)}><Icon /><span>{label}</span></button>)}<span className="command-group-title">SYSTEM CONTROLS</span><button className="command-item" onClick={toggleRecruiter}><Activity /><span>{recruiterMode ? 'Exit' : 'Enter'} Recruiter Mode</span></button><button className="command-item" onClick={toggleTheme}>{isDark ? <Sun /> : <Moon />}<span>Switch to {isDark ? 'light' : 'dark'} theme</span></button></>}<span className="command-group-title">PROJECT WORLDS</span>{found.map(project => <button className="command-item" key={project.id} onClick={() => { onClose(); onSelectProject(project); }}><FolderGit2 /><span><b>{project.title}</b><small>{project.technologies.slice(0, 3).join(' · ')}</small></span></button>)}</div><div className="command-footer"><span><kbd>ESC</kbd> close</span><span><kbd>⌘K</kbd> toggle</span></div></section></div>;
}
