import { useState } from 'react';
import { AlertCircle, ArrowUpRight, CheckCircle2, Mail, Send } from 'lucide-react';
import { sendEmail } from '../../services/emailService';
import type { ContactFormData } from '../../types';
export default function Contact() {
  const [form, setForm] = useState<ContactFormData>({ name: '', email: '', message: '' });
  const [status, setStatus] = useState<'idle'|'sending'|'success'|'error'>('idle');
  const submit = async (e: React.FormEvent<HTMLFormElement>) => { e.preventDefault(); if (new FormData(e.currentTarget).get('_gotcha')) return; setStatus('sending'); const ok = await sendEmail(form); setStatus(ok ? 'success' : 'error'); if (ok) setForm({ name: '', email: '', message: '' }); };
  const change = (e: React.ChangeEvent<HTMLInputElement|HTMLTextAreaElement>) => setForm(v => ({ ...v, [e.target.name]: e.target.value }));
  return <section id="contact" className="contact-section section-pad"><div className="contact-orb" aria-hidden="true"/><div className="section-kicker"><span>05</span> CONTACT / TRANSMISSION</div><div className="contact-grid"><div className="contact-copy"><h2>Have an idea?<br/><em>Let’s give it depth.</em></h2><p>Tell me what you’re building, what’s getting in the way, or simply say hello. I usually respond within 24 hours.</p><a href="mailto:ramprakash777.sah@gmail.com"><Mail/> ramprakash777.sah@gmail.com <ArrowUpRight/></a><div className="availability"><span className="live-dot"/><div><b>Open to thoughtful work</b><small>Freelance projects and collaborations</small></div></div></div><form className="contact-form" onSubmit={submit}><div className="form-head"><span>MESSAGE CHANNEL</span><i>SECURE / FORMSPREE</i></div><div className="honeypot" aria-hidden="true"><label>Leave this field empty<input name="_gotcha" tabIndex={-1} autoComplete="off"/></label></div><label><span>YOUR NAME</span><input required name="name" autoComplete="name" value={form.name} onChange={change} placeholder="What should I call you?"/></label><label><span>EMAIL ADDRESS</span><input required type="email" name="email" autoComplete="email" value={form.email} onChange={change} placeholder="you@company.com"/></label><label><span>PROJECT / MESSAGE</span><textarea required rows={5} name="message" value={form.message} onChange={change} placeholder="A little about your idea, timeline, or challenge..."/></label><button className="primary-btn" disabled={status === 'sending'}>{status === 'sending' ? 'Transmitting...' : <>Send message <Send/></>}</button><div aria-live="polite">{status === 'success' && <p className="form-status success"><CheckCircle2/> Message received. I’ll be in touch soon.</p>}{status === 'error' && <p className="form-status error"><AlertCircle/> Transmission failed. Please email me directly.</p>}</div></form></div></section>;
}
